---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ttl-operator
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ttl-operator
rules:
- apiGroups:
    - "*"
  resources:
    - "*"
  verbs:
    - get
    - list
    - watch
    - delete
- apiGroups:
    - fpetkovski.io
  resources:
    - ttlcontrollers
  verbs:
    - update
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ttl-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ttl-operator
subjects:
  - kind: ServiceAccount
    name: ttl-operator
    namespace: kube-system
