---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ttl-controller
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ttl-controller
rules:
- apiGroups:
    - "*"
  resources:
    - "*"
  verbs:
    - get
    - list
    - watch
    - update
    - delete
- apiGroups:
    - fpetkovski.io
  resources:
    - ttlpolicies
  verbs:
    - update
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ttl-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ttl-controller
subjects:
  - kind: ServiceAccount
    name: ttl-controller
    namespace: kube-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ttl-controller
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ttl-controller
  template:
    metadata:
      labels:
        name: ttl-controller
    spec:
      serviceAccountName: ttl-controller
      containers:
        - name: ttl-controller
          image: fpetkovski/ttl-controller:0.4.0
          args:
            - --v=4
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "0.5"
              memory: "128Mi"
            limits:
              cpu: "0.5"
              memory: "128Mi"