---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ttl-operator
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ttl-operator
rules:
- apiGroups:
    - "*"
  resources:
    - "*"
  verbs:
    - get
    - list
    - watch
    - delete
- apiGroups:
    - fpetkovski.io
  resources:
    - ttlcontrollers
  verbs:
    - update
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ttl-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ttl-operator
subjects:
  - kind: ServiceAccount
    name: ttl-operator
    namespace: kube-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ttl-operator
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ttl-operator
  template:
    metadata:
      labels:
        name: ttl-operator
    spec:
      serviceAccountName: ttl-operator
      containers:
        - name: ttl-operator
          image: fpetkovski/ttl-operator:0.2.0
          args:
            - --v=4
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "0.5"
              memory: "128Mi"
            limits:
              cpu: "0.5"
              memory: "128Mi"